packages:
  - "packages/*"

catalog:
  "@arethetypeswrong/cli": "^0.18.2"
  "@changesets/cli": "^2.29.8"
  "@types/node": "^25.3.5"
  husky: "^9.1.7"
  lint-staged: "^16.2.7"
  npm-check-updates: "^19.1.2"
  oxfmt: "^0.36.0"
  oxlint: "^1.51.0"
  oxlint-tsgolint: "^0.16.0"
  tsup: "^8.5.1"
  typescript: "^5.9.3"
  vitest: "^4.0.15"
