/**
 * Utilities for building TypeScript source code strings.
 */

/** Indent a block of text by a given number of tabs */
export function indent(text: string, level: number): string {
	const prefix = "\t".repeat(level);
	return text
		.split("\n")
		.map((line) => (line.trim() ? prefix + line : line))
		.join("\n");
}

/** Build an import statement */
export function buildImport(names: string[], from: string, isType = false): string {
	if (names.length === 0) return "";
	const sorted = [...new Set(names)].sort();
	const typePrefix = isType ? "type " : "";
	if (sorted.length <= 3) {
		return `import ${typePrefix}{ ${sorted.join(", ")} } from "${from}";`;
	}
	const items = sorted.map((n) => `\t${n},`).join("\n");
	return `import ${typePrefix}{\n${items}\n} from "${from}";`;
}

/** Build a decorator call with options object */
export function buildDecorator(name: string, options?: Record<string, unknown>): string {
	if (!options || Object.keys(options).length === 0) {
		return `@${name}()`;
	}

	const entries = Object.entries(options).filter(([, v]) => v !== undefined);

	if (entries.length === 0) {
		return `@${name}()`;
	}

	const optionStr = entries.map(([k, v]) => `${k}: ${formatValue(v)}`).join(", ");

	// Simple single-option or short options → inline
	if (optionStr.length < 60) {
		return `@${name}({ ${optionStr} })`;
	}

	// Multi-line for complex options
	const lines = entries.map(([k, v]) => `\t\t${k}: ${formatValue(v)},`).join("\n");
	return `@${name}({\n${lines}\n\t})`;
}

/** Format a value for use in generated code */
export function formatValue(value: unknown): string {
	if (typeof value === "string") return value;
	if (typeof value === "number" || typeof value === "boolean") return String(value);
	if (value instanceof RegExp) return value.toString();
	if (Array.isArray(value)) {
		const items = value.map((v) => formatValue(v)).join(", ");
		return `[${items}]`;
	}
	if (typeof value === "object" && value !== null) {
		const entries = Object.entries(value)
			.filter(([, v]) => v !== undefined)
			.map(([k, v]) => `${k}: ${formatValue(v)}`);
		return `{ ${entries.join(", ")} }`;
	}
	return String(value);
}

/** Build a class property declaration line */
export function buildProperty(name: string, type: string, initializer: string, optional = false): string {
	const optionalMark = optional ? "?" : "";
	return `${name}${optionalMark}: ${type} = ${initializer};`;
}

/** Build the auto-generated file header */
export function buildFileHeader(xsdPath: string): string {
	return [
		"// ──────────────────────────────────────────────────",
		"// AUTO-GENERATED by @cerios/xml-poto-codegen",
		`// Source: ${xsdPath}`,
		"// Do not edit manually.",
		"// ──────────────────────────────────────────────────",
		"",
	].join("\n");
}

/** Convert a class name to a kebab-case filename */
export function toKebabCase(name: string): string {
	return name
		.replace(/([a-z0-9])([A-Z])/g, "$1-$2")
		.replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
		.toLowerCase();
}
