/**
 * Utilities for building TypeScript source code strings.
 */

/** Indent a block of text by a given number of tabs */
export function indent(text: string, level: number): string {
	const prefix = "\t".repeat(level);
	return text
		.split("\n")
		.map((line) => (line.trim() ? prefix + line : line))
		.join("\n");
}

/** Build an import statement */
export function buildImport(names: string[], from: string, isType = false): string {
	if (names.length === 0) return "";
	const sorted = [...new Set(names)].sort();
	const typePrefix = isType ? "type " : "";
	if (sorted.length <= 3) {
		return `import ${typePrefix}{ ${sorted.join(", ")} } from "${from}";`;
	}
	const items = sorted.map((n) => `\t${n},`).join("\n");
	return `import ${typePrefix}{\n${items}\n} from "${from}";`;
}

/**
 * Build a decorator call with options object.
 *
 * `indentLevel` is the indentation of the line the decorator is emitted on, in
 * tabs. It only affects the multi-line form: continuation lines are indented one
 * level deeper and the closing `})` back to `indentLevel`. The caller supplies the
 * prefix for the *first* line, so a property decorator (default, level 1) keeps its
 * historical shape while a class decorator at column 0 passes 0.
 */
export function buildDecorator(name: string, options?: Record<string, unknown>, indentLevel = 1): string {
	if (!options || Object.keys(options).length === 0) {
		return `@${name}()`;
	}

	const entries = Object.entries(options).filter(([, v]) => v !== undefined);

	if (entries.length === 0) {
		return `@${name}()`;
	}

	const optionStr = entries.map(([k, v]) => `${k}: ${formatValue(v)}`).join(", ");

	// Simple single-option or short options → inline
	if (optionStr.length < 60) {
		return `@${name}({ ${optionStr} })`;
	}

	// Multi-line for complex options
	const optionIndent = "\t".repeat(indentLevel + 1);
	const closeIndent = "\t".repeat(indentLevel);
	const lines = entries.map(([k, v]) => `${optionIndent}${k}: ${formatValue(v)},`).join("\n");
	return `@${name}({\n${lines}\n${closeIndent}})`;
}

/** Format a value for use in generated code */
export function formatValue(value: unknown): string {
	if (typeof value === "string") return value;
	if (typeof value === "number" || typeof value === "boolean") return String(value);
	if (value instanceof RegExp) return value.toString();
	if (Array.isArray(value)) {
		const items = value.map((v) => formatValue(v)).join(", ");
		return `[${items}]`;
	}
	if (typeof value === "object" && value !== null) {
		const entries = Object.entries(value)
			.filter(([, v]) => v !== undefined)
			.map(([k, v]) => `${k}: ${formatValue(v)}`);
		return `{ ${entries.join(", ")} }`;
	}
	return String(value);
}

/** Build a JSDoc comment block from documentation text (lines wrapped at ~100 chars) */
export function buildJsDoc(text: string): string {
	const escaped = text.replace(/\*\//g, "*\\/");
	const lines: string[] = [];
	for (const paragraph of escaped.split("\n")) {
		lines.push(...wrapText(paragraph, 100));
	}

	if (lines.length === 1) {
		return `/** ${lines[0]} */`;
	}
	return ["/**", ...lines.map((l) => ` * ${l}`), " */"].join("\n");
}

function wrapText(text: string, width: number): string[] {
	const words = text.split(/\s+/).filter(Boolean);
	const lines: string[] = [];
	let current = "";
	for (const word of words) {
		if (current && current.length + word.length + 1 > width) {
			lines.push(current);
			current = word;
		} else {
			current = current ? `${current} ${word}` : word;
		}
	}
	if (current) lines.push(current);
	return lines;
}

/** Build a class property declaration line */
export function buildProperty(
	name: string,
	type: string,
	initializer?: string,
	optional = false,
	definite = false,
): string {
	const marker = optional ? "?" : definite ? "!" : "";
	if (initializer === undefined) {
		return `${name}${marker}: ${type};`;
	}
	return `${name}${marker}: ${type} = ${initializer};`;
}

/** Build the auto-generated file header */
export function buildFileHeader(xsdPath: string): string {
	return [
		"// ──────────────────────────────────────────────────",
		"// AUTO-GENERATED by @cerios/xml-poto-codegen",
		`// Source: ${xsdPath}`,
		"// Do not edit manually.",
		"// ──────────────────────────────────────────────────",
		"",
	].join("\n");
}

/** Convert a class name to a kebab-case filename */
export function toKebabCase(name: string): string {
	return name
		.replace(/([a-z0-9])([A-Z])/g, "$1-$2")
		.replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
		.toLowerCase();
}
